Repository MatTerra/IngressoNet, pull requests merged in 2019-09, with the labels that each got.

#12 Card n validation
  .gitignore
  IngressoNet.pro
  src/cartao.cpp
  src/cartao.h
  src/main.cpp
  src/teste.cpp
  src/teste.h
  test/Cartao.test.cpp
  test/test.pro
  test/testesunitarios.cpp
Labels: Validation, enhancement

#17 Readme update
  .gitignore
  IngressoNet.pro
  README.md
  README2.md
Labels: documentation, enhancement

#33 Persistance helper
  doc/IngressoNet.asta
  src/persistancehelper.h
  src/src.pro
Labels: enhancement

#34 Db helper
  doc/IngressoNet.asta
  src/exceptions/notabletoconnectexception.h
  src/mysqlhelper.cpp
  src/mysqlhelper.h
  src/persistancehelper.h
  src/src.pro
  src/usuariodao.cpp
  src/usuariodao.h
  test/MySQLHelper/MySQLHelper.pro
  test/MySQLHelper/testemysqlhelper.cpp
  test/test.pro
Labels: enhancement

#36 Usuario dao
  IngressoNet.pro
  db/ingresso_net_db.sql
  doc/ingressoNetDb.mwb
  src/genericdao.h
  src/mysqlhelper.cpp
  src/mysqlhelper.h
  src/notabletoconnectexception.h
  src/src.pro
  src/usuariodao.cpp
  src/usuariodao.h
  test/Cartao/testecartao
  test/Cidade/testecidade
  test/MySQLHelper/testemysqlhelper
  test/Usuario/testeusuario
  test/Usuario/testeusuario.cpp
  test/UsuarioDAO/UsuarioDAO.pro
  test/UsuarioDAO/testeusuariodao
  test/UsuarioDAO/testeusuariodao.cpp
  test/test.pro
Labels: enhancement

#39 Cidade dao
  src/cartaodao.h
  src/cidadedao.cpp
  src/cidadedao.h
  test/CartaoDAO/CartaoDAO.pro
  test/CidadeDAO/CidadeDAO.pro
  test/CidadeDAO/testecidadedao.cpp
  test/test.pro
Labels: Validation, documentation, enhancement

#40 Exportado modelo do banco de dados em PDF. Closes #5
  doc/IngressoNet.asta
  doc/ModeloBancoDeDados.pdf
  doc/ingressoNetDb.mwb
Labels: documentation

#41 Diagrama de classes em PDF adicionado
  doc/DiagramaDeClasses.pdf
Labels: documentation

#43 Partida
  src/partida.cpp
  src/partida.h
  test/Partida/Partida.pro
  test/Partida/testepartida.cpp
  test/test.pro
Labels: Validation, enhancement

#46 Partidadao
  src/partidadao.cpp
  src/partidadao.h
  src/usuariodao.h
  test/Partida/testepartida.cpp
  test/PartidaDAO/PartidaDAO.pro
  test/PartidaDAO/testepartidadao.cpp
  test/test.pro
Labels: Validation, enhancement

#48 IngressoDAO
  src/ingressodao.cpp
  src/ingressodao.h
  test/IngressoDAO/IngressoDAO.pro
  test/IngressoDAO/testeingressodao.cpp
  test/test.pro
Labels: Validation, documentation, enhancement

#51 Classe jogo
  doc/IngressoNet.asta
  src/jogo.h
  src/partida.h
Labels: documentation, enhancement

#49 JogoDAO
  src/cartaodao.h
  src/jogodao.cpp
  src/jogodao.h
  test/JogoDAO/JogoDAO.pro
  test/JogoDAO/testejogodao.cpp
  test/test.pro
Labels: Validation, documentation, enhancement
